# Generated by Django 5.1.7 on 2025-03-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0004_alter_planets_surface_water'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planets',
            name='surface_water',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
