# Generated by Django 5.1.7 on 2025-03-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0009_alter_planets_climate_alter_planets_diameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planets',
            name='terrain',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
