# Generated by Django 5.1.7 on 2025-03-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex10', '0002_alter_planets_created_alter_planets_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
