# Generated by Django 5.1.7 on 2025-03-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex10', '0004_alter_movies_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='episode_nb',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
