# Generated by Django 5.1.7 on 2025-03-26 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0003_tip_downvotes_tip_upvotes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tip',
            options={'permissions': [('can_downvote_tip', 'Can downvote tip')]},
        ),
    ]
