# Generated by Django 5.1.7 on 2025-03-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0004_alter_tip_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reputation',
            field=models.IntegerField(default=0),
        ),
    ]
